language: rust
jobs:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - arch: arm64
      rust: nightly
cache:
  directories:
    - /home/travis/.cargo
install:
  - rustup component add clippy; true
script:
  - cargo clippy -- -D warnings; true
  - cargo test
