language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - /home/travis/.cargo
install:
  - rustup component add clippy; true
script:
  - cargo clippy -- -D warnings
  - cargo test
